;  [ This translation created 10-Feb-83 by Version 4.3 ]
	.radix 8
;  To be safe
; CSEG CODESG (public)
; Assuming segment CS:CSEG
	include OEM.H

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; KANJ86 - KANJI String Function Support for Basic-86 ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; 
; 
; --------- --- ---- -- ---------
; COPYRIGHT (C) 1982 BY MICROSOFT
; --------- --- ---- -- ---------
; 
;         Author: Tom Corbett - Microsoft Inc.  -  April 28, 1982
; 
;         
	include GIO86U
; contains DB definition
	include MSDOSU
IF CPM86
	include CPM86U
ENDIF
	PUBLIC KTNFN
KTNFN:
	PUBLIC JISFN
JISFN:
	PUBLIC KLENFN
KLENFN:
	PUBLIC KPOSFN
KPOSFN:
	EXTERN SNERR:NEAR
	JP SNERR
