;  [ This translation created 10-Feb-83 by Version 4.3 ]
	.radix 8
;  To be safe
; CSEG CODESG (public)
; Assuming segment CS:CSEG
	include OEM.H

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; SCNEDT  Screen Oriented Editor for GW-BASIC ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


;;; DATA DEFINITIONS ;;;

; 
;         --------- --- ---- -- ---------
;         COPYRIGHT (C) 1982 BY MICROSOFT
;         --------- --- ---- -- ---------
;         
	include GIO86U
	.radix 8
; OEM IFNDEF'S:
	MELCO=0
	HAL=0
; GENERIC IFNDEF'S:
	TERMSW=0
	HLPTRP=0
	STPTRP=0
	HLPEDT=0
	SCRKEY=0
	NMPAGE=0
	IBMCSR=IBMLIK
; INTERNAL ROUTINES:
	PUBLIC PINLIN
;  Program line input
; on exit:       BX=addr of input -1
	PUBLIC INLIN
;  BASIC INPUT Statements line input
; on exit:       BX=addr of input -1
	PUBLIC SINLIN
;  BASIC INPUT Statements redo line input
; on exit:       BX=addr of input -1
	PUBLIC QINLIN
;  BASIC INPUT Statements with output of "?" first
; on exit:       BX=addr of input -1
	PUBLIC SCNSEM
;  BASIC INPUT statement scan for semicolon
; on exit:       SEMFLG flag set
	PUBLIC EDTBRK
;  BASIC received break, reinitialize routine
	PUBLIC ERREDT
;  BASIC Syntax error auto-edit on ERRLIN
; on exit:       Removes return and jumps to MAIN after
;                listing ERRLIN and positioning cursor at
;                start of line.
	PUBLIC EDIT
;  EDIT Statement
; on exit:       Same as ERREDT, except takes line number
;                to list as argument.
;        INTERN  EDITRT          ; AUTO Program line input processing
; on exit:       BX=addr of input(BUF)
;                it also puts PSW on stack with carry
;                set and jumps to EDENT for exit
; EXTERNAL ROUTINES:
	EXTERN OUTDO:NEAR
;  Character output(GIO86)
	EXTERN KEYIN:NEAR
;  Key input(expands any string keys-GIOKYB)
	EXTERN SCNMRK:NEAR
;  Mark current posn as start of line(SCNDRV)
	EXTERN SCNRDL:NEAR
;  Read current logical line(SCNDRV)
	EXTERN CRDO:NEAR
;  BASIC new line routine
	EXTERN CHRGTR:NEAR
;  BASIC character scan routine
; DATA (DEFINED IN RAM MODULE)
; CSEG DATASG (public)
; Assuming segment DS:DSEG
	EXTERN F_EDPG:WORD
;  Flag - =^O377 indicates program statement edit
	EXTERN SEMFLG:WORD
;  Flag - zero indicates INPUT; statement(no crlf
;        at end of input line)
	EXTERN F_INST:WORD
;  Flag - =^O377 indicates insert mode
	EXTERN BUF:WORD
;  Buffer where line of data is returned
;    NOTE: assumes non-blank at BUF-1
	EXTERN F_EDIT:WORD
;  Flag - non-zero indicates INLIN active
	EXTERN AUTFLG:WORD
;  AUTO mode flag
	EXTERN CSRX:WORD
;  Cursor column (1..n)
	EXTERN CSRY:WORD
;  Cursor line (1..n)
; LITERALS NEEDED ELSEWHERE
	PUBLIC CHRLNF
;  Line feed character
	PUBLIC CHRRET
;  Carriage return character
; CHARACTER DEFINITIONS
; 
; 
	CHREDT=1
;  EDiT
	CHRBKW=2
;  BacK Word
	CHRCAN=3
;  CANcel
	CHRHCN=4
;  Hard CaNcel
	CHRCLE=5
;  CLear to End of line
	CHRFDW=6
;  ForwarD Word
	CHRBEL=7
;  BELl
	CHRBAK=8D
;  BAcKspace
	CHRTAB=9D
;  TAB
	CHRLNF=10D
;  LiNeFeed
	CHRHOM=11D
;  HOMe
	CHRERA=12D
;  ERAse
	CHRRET=13D
;  RETurn
	CHRAPP=14D
;  APPend
	CHRINS=18D
;  INSert
	CHRLDL=21D
;  Line DeLete
	CHRADV=28D
;  cursor RiGhT
	CHRREG=29D
;  cursor LeFT
	CHRUP=30D
;  cursor UP
	CHRDWN=31D
;  cursor DoWN
	CHRDEL=127D
;  DELete

;;; Entry points for editing ;;;

; ENTRY: PINLIN, QINLIN, INLIN, SINLIN
; 
; PROGRAM STATEMENT INPUT
	PUBLIC PINLIN
PINLIN:
	CALL DSKCHI		;  Don't return if Loading ASCII File
	SCF		;  Indicate program statement input
	JR INLIN0
; PRINT "?" BEFORE GETTING INPUT
	PUBLIC QINLIN
QINLIN:
	LD A, LOW "?"
	CALL OUTDO		;  Output a "?"
	LD A, LOW " "
	CALL OUTDO		;  Followed by a space
; INPUT STATEMENT
	PUBLIC INLIN
INLIN:
; INPUT STATEMENT REDO
	PUBLIC SINLIN
SINLIN:
	OR A		;  Indicate INPUT statement line input
INLIN0:
	SBC A		;  If INPUT statement AL=0, else AL=-1
	LD (F_EDPG), A		;  Save flag
	LD A, (F_EDIT)		;  Get old value of F.EDIT(in case of EDIT statement)
	LD (F_EDIT), LOW 255		;  Indicate executing INLIN
	CALL SCNMRK		;  Set up for edit
;    If AL=1 then move cursor to start of logical
;        line which preceeds current.
;    Else if ZF=1 then set up FSTPOS, LSTPOS
;         if ZF=0 then FSTPOS=0,0; LSTPOS=max,max

;;; MAIN loop of editor ;;;

; WHILE EOL.NE.TRUE BEGIN
; ** GET A KEY
INLLOP:
	EXTERN STCTYP:NEAR
	SCF
	CCF		;  Signal for insert or overwrite cursor
	CALL STCTYP		;  Set new cursor type
	CALL KEYIN		;  AX=key value
; At this point we can have three classes of characters:
;    CF=1 indicates 2 byte char with 2 sub classes:
;        AH=FF indicates editor control function
;        AH<>FF indicates 2 byte character to echo
;    CF=0 indicates 1 or 3 byte key
;        AL=FF indicates a 3 byte key with scan code in DX - these are ignored
;        AL<>FF indicates a 1 byte key to echo, except if char is CR.
	JP C, INL2BY		;  BRIF 2-byte character, check for editor controls
	CP CHRRET
	JP Z, INLRET		;  BRIF CR, terminate line input
; ** IF CURRENT_CHAR IS SPECIAL THREE BYTE CHAR
	CP 254		;  Test for 3-byte character
; ** *** IGNORE THIS CHAR
	JP Z, INLLOP		;  BRIF to ignore 3-byte character
	JR INLOP0		;  Not 3-bytes, just echo single byte
INL2BY:
; ** IF CURRENT_CHAR IS CONTROL_CHAR
	; CMP AH, 255D
	JP NZ, INLOP0		;  BRIF not editor control character, echo char
	CP 127
	JP Z, INLP0		;  BRIF is a control character
	CP " "
	JP NC, INLOP0		;  BRIF is not a control character
INLP0:
; ** IF CURRENT_CHAR IS <CR> RETURN CURRENT LOGICAL LINE
	CP CHRRET
	JP Z, INLRET		;  BRIF is carriage return(EOL)
; ** IF (CURRENT_CHAR=<HELP> AND INPUT_MODE=PROGRAM) DO EDIT ON KBUF
	CP CHREDT
	JP NZ, INLOP0
	JP INLHLP		;  BRIF help char, do edit on KBUF
; Echo character in AX
INLOP0:
	OR A
	JP Z, INLOP3		;  Single byte character
	; FIXME: This is invalid Z80
	LD C', A
	LD A, B'
	LD B', C'		;  Output AH first
	CALL OUTDO		;  Output a char
	; FIXME: This is invalid Z80
	LD C', A
	LD A, B'
	LD B', C'		;  Restore AL
INLOP3:
	CALL OUTDO		;  Output a char
	JR INLLOP
; ** END
; SCAN FOR SEMICOLON
; 
SCNSEM:
	CP ";"
	JP NZ, SCNSMR		;  BRIF not semicolon, return
	LD (SEMFLG), A
	JP CHRGTR		;  Skip semicolon and return
SCNSMR:
	RET

;;; Exit ;;;


;;; return current logical line ;;;

; READ LOGICAL LINE INTO BUF
INLRET:
	LD HL, (BUF)		;  Put data into BUF
	LD BC, 255		;  CX=Max number of bytes to move
	; TEST {'type': 'instruction', 'op': 'TEST', 'operands': (('BYTE', 'PTR', 'F_EDPG'), ('LOW', 255)), 'comment': ' Set zero flag if program statement input', 'id': 236}		;  Set zero flag if program statement input
	PUSH AF
	LD E, (CSRY)		;  (DH,DL) = (CSRX,CSRY)
	LD D, (CSRX)
	CALL SCNRDL		;  Read the logical line into BUF
;  BX=address of last char in BUF plus one
; IF PROGRAM_STATEMENT_INPUT BEGIN
	POP AF
	JP Z, INCRTX		;  BRIF not statement input
; ** WHILE POSN.NE.BEGIN_OF_LINE AND [POSN].NE.BLANK AND [POSN].NE.LF BEGIN
	PUSH BC
	POP HL
	
	; SUB CX, ('OFFSET', 'BUF')		;  CX=count of chars in BUF
	JP Z, INCRTX		;  BUF is empty
	PUSH IX
	LD IXH, H
	LD IXL, L
	DEC IX		;  Start scan at last valid data
INLOT0:
	LD A, LOW " "
; ** *** POSN=POSN-1
INLOT1:
	; STD		;  Scan backwards
	; REPE SCASB		;  This works for blank line("," at BUF-1)
	INC IX		;  [DI] = last valid data
	LD A, LOW " "
	; CMP 0[DI], AL
	JP Z, INLOT2		;  BRIF more trailing blanks
	LD A, LOW OFFSET CHRLNF
	CP (IX+0)
	JP NZ, INLOT3		;  BRIF not more trailing linefeeds
INLOT2:
	OR A
	JP NZ, INLOT1		;  BRIF not at beginning of buffer
; ** *** END
; ** END
INLOT3:
	LD H, IXH
	LD LL, IX
	POP IX
	INC HL
INCRTX:
	LD BYTE PTR 0 [BX], LOW 0		;  Terminate BUF
; ** UPDATE CURSOR POSN, RETURN
	; TEST {'type': 'instruction', 'op': 'TEST', 'operands': (('BYTE', 'PTR', 'SEMFLG'), ('LOW', 255)), 'comment': None, 'id': 277}
	JP NZ, INCRTF		;  BRIF if INPUT<semicolon> statement
	LD AX, OFFSET CHRAPP
	CALL OUTDO		;  Move to end of logical
	LD (F_EDIT), LOW 0
	CALL CRDO		;  Move to first posn beyond this logical
INCRTF:
	LD HL, (BUF-1)		;  Return BUF - 1
	PUSH AF
	CALL CLRFLG		;  Clear miscellaneous status flags
	POP AF
	RET
; SUBROUTINE EDTBRK              ; Routine which initializes when break detected
; **                             ; This is called by the STOP code
; **
EDTBRK:
	EXTERN SETCSR:NEAR
; CSEG DATASG (public)
	EXTERN CSRTYP:WORD
	LD (CSRTYP), LOW 0		;  Indicate cursor off
	CALL SETCSR
	CALL CLRFLG		;  Clear editor flags
	PUSH AF
	LD A, LOW OFFSET CHRAPP
	LD (F_EDIT), A
	CALL OUTDO		;  Move cursor to end of logical line
	LD (F_EDIT), LOW 0		;  Reset edit mode
	CALL CRDO		;  Move cursor to next physical line
	POP AF
	LD (AUTFLG), LOW 0		;  Reset AUTO mode
	RET
; ** END SUBROUTINE EDTBRK
; SUBROUTINE CLRFLG              ; Routine which clears flags
; **
CLRFLG:
	LD (F_EDIT), LOW 0		;  No longer in INLIN
	LD (F_EDPG), LOW 0		;  Not program edit
	LD (F_INST), LOW 0		;  Not insert mode
	LD (SEMFLG), LOW 0		;  Not INPUT; statement
	RET
; ** END SUBROUTINE CLRFLG

;;; EDIT code ;;;

	EXTERN MAIN:NEAR
	EXTERN LINSPC:NEAR
	EXTERN FNDLIN:NEAR
	EXTERN DEPTR:NEAR
	EXTERN LISPRT:NEAR
	EXTERN LINPRT:NEAR
	EXTERN FCERR:NEAR
	EXTERN USERR:NEAR
	EXTERN BUFLIN:NEAR
; CSEG DATASG (public)
	EXTERN DOT:WORD
	EXTERN ERRFLG:WORD
	EXTERN ERRLIN:WORD
; EDIT COMMAND
; 
	PUBLIC EDIT
EDIT:
	CALL LINSPC		;  LINE NUMBER IN DE
	JP NZ, EFCERR		;  STATEMENT MUST HAVE ENDED
EREDIT:
	POP HL		;  REMOVE NEWSTT(OR CALL FROM MAIN)RETURN
	LD (WORDPTRDOT), DE
	CALL FNDLIN		;  FIND LINE
	JP NC, EUSERR		;  LINE DOES NOT EXIST
	PUSH HL
	POP BC
			;  CX=LINE PTR
ERED2:
	INC HL
	INC HL
	LD DE, WORD PTR 0 [BX]		;  DE=LINE NUMBER
	INC HL
	INC HL
ERED3:
	PUSH HL
	LD (F_EDIT), LOW 1		;  SET FLAG INDICATING IN EDIT MODE
;  (FORCES OPEN LINES DURING LIST)
;  (AND TELLS INLIN TO START AT BEGIN OF LOGICAL)
	EX DE, HL
ERED4:
	CALL LINPRT		;  PRINT THE LINE NUMBER
	POP HL
	PUSH BC
	LD B, A
	LD A, 9D
	CP (HL)
	LD A, B
	POP BC		;  LINE START WITH TAB?
	JP Z, ERED5
	LD A, LOW " "
	CALL OUTDO		;  NO, PUT SPACE OUT
; ENTRY FOR EDIT ON KBUF IS HERE
ERED5:
	LD (F_EDIT), LOW 1		;  SET FLAG INDICATING IN EDIT MODE
;  (FORCES OPEN LINES DURING LIST)
;  (AND TELLS INLIN TO START AT BEGIN OF LOGICAL)
	CALL BUFLIN		;  PUT LINE IN BUF AND SET UP HLPBFA
	LD HL, (BUF)
	CALL LISPRT		;  PRINT THE LINE AND SET UP HLPCSR
	LD L, (CSRY)
	LD H, (CSRX)
	JP MAIN
EFCERR:
	JP FCERR		;  Indirect jump to FCERR
EUSERR:
	JP USERR		;  Indirect jump to USERR
; Help key edit
; 
INLHLP:
	; TEST {'type': 'instruction', 'op': 'TEST', 'operands': (('BYTE', 'PTR', 'F_EDPG'), ('LOW', 255)), 'comment': None, 'id': 381}
	JP NZ, INLHL0		;  BRIF do help edit on program statement
; Help during input statement
	JP INLOP3		;  Just output char
; DO EDIT ON DOT
INLHL0:
	POP AF		;  Remove call to this routine
; See if edit on error line number
	LD DE, (WORDPTRERRLIN)
	CALL ERRED2		;  If exists,do edit on error line number
; See if edit on current line number
	LD DE, (WORDPTRCURLIN)
	CALL ERRED2		;  If exists,do edit on current line number
; ERRLIN AND CURLIN ARE DIRECT, DO EDIT ON KBUF
; CSEG DATASG (public)
	EXTERN KBUF:WORD
	EXTERN CURLIN:WORD
	EXTERN SCNEXT:NEAR
	EXTERN DEPTR:NEAR
	CALL DEPTR		;  Remove line pointers from program
	LD HL, (KBUF)
	PUSH HL
	DEC HL
	CALL SCNEXT		;  Remove any line pointers from KBUF
	POP HL
	JR ERED5
; AUTOMATIC EDIT FOR ERRORS
; 
	PUBLIC ERREDT
ERREDT:
	LD (ERRFLG), A		;  Reset the flag to call edit
	LD DE, (WORDPTRERRLIN)		;  Get the line number
ERRED2:
	PUSH HL
	PUSH DE
	LD HL, 65535D
	OR A
	SBC DE, HL
	ADD DE, HL
	POP DE
	POP HL		;  See if it was direct
	JP Z, ERRED3		;  Go back if direct
	OR A
	JP Z, ERRED3		;  Go back if zero
	JP EREDIT
ERRED3:
	RET

;;; ASCII LOAD and SAVE line handler ;;;

; LOAD ASCII:
;   PROGRAM LINE INPUT FROM DISK
; 
	EXTERN ISFLIO:NEAR
	EXTERN OUTDO:NEAR
	EXTERN INCHR:NEAR
	EXTERN LBOERR:NEAR
DSKCHI:
	CALL ISFLIO		;  Set FLAGS.NZ if PTRFIL points to active file
	JP NZ, ISLOAD		;  BRIF LOAD statement
	RET		;  If so use special screen io
ISLOAD:
	POP AF		;  Discard Return Address
	LD C, LOW OFFSET BUFLEN		;  Setup the maximum character count
	LD HL, (BUF)		;  Place we are going to stoer the line
LOPBUF:
	CALL INCHR		;  Get a character from the file
;  (will call indskc and handle eof)
	LD BYTE PTR 0 [BX], A		;  Store the character
	CP 13		;  Is it the end (a CR)
	JP NZ, INOTCR		;  Not a [CR]
Exception: Don't know how to generate CMP: {'type': 'instruction', 'op': 'CMP', 'operands': (('BYTE', 'PTR', '-1', '[BX]'), ('LOW', 10)), 'comment': ' Preceeded by a line feed?', 'id': 443}
Traceback (most recent call last):
  File "/Users/mac/Library/Python/3.9/lib/python/site-packages/z80conv-0.0.1-py3.9.egg/z80conv/conv.py", line 20, in main
    for line in writer.lines():
  File "/Users/mac/Library/Python/3.9/lib/python/site-packages/z80conv-0.0.1-py3.9.egg/z80conv/writer.py", line 27, in lines
    line = getattr(self, generator)(token)
  File "/Users/mac/Library/Python/3.9/lib/python/site-packages/z80conv-0.0.1-py3.9.egg/z80conv/writer.py", line 801, in _gen_instruction
    instr = getattr(self, '_gen_instruction_' + op.lower())(token)
  File "/Users/mac/Library/Python/3.9/lib/python/site-packages/z80conv-0.0.1-py3.9.egg/z80conv/writer.py", line 264, in _gen_instruction_cmp
    raise SyntaxError("Don't know how to generate CMP: %s" % token)
SyntaxError: Don't know how to generate CMP: {'type': 'instruction', 'op': 'CMP', 'operands': (('BYTE', 'PTR', '-1', '[BX]'), ('LOW', 10)), 'comment': ' Preceeded by a line feed?', 'id': 443}
